#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_4x12( \
        XXXXXXX, XXXXXXX, KC_W   , KC_F   , KC_P   , KC_G   ,      KC_J   , KC_L   , KC_U   , KC_Y   , XXXXXXX, KC_BSPC, \
        KC_ESC , KC_A   , KC_R   , KC_S   , KC_T   , KC_D   ,      KC_H   , KC_N   , KC_E   , KC_I   , KC_O   ,  KC_ENT, \
        XXXXXXX, KC_Z   , KC_X   , KC_C   , KC_V   , KC_B   ,      KC_K   , KC_M   , KC_COMM, KC_DOT , KC_Q   , XXXXXXX, \
        KC_LSFT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      KC_SPC , MO(1)  , XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX  \
    ), 
    [1] = LAYOUT_ortho_4x12( \
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      KC_LEFT, KC_DOWN, KC_UP  , KC_RGHT, XXXXXXX, XXXXXXX, \
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,      XXXXXXX, _______, QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX  \
    ), 
};
