theme = "dark_plus"
# theme = "base16_transparent"
# theme = "dark_high_contrast"
# theme = "heisenberg"
# theme = "molokai"
# theme = "onedarker"
# theme = "catppuccin_latte"
# theme = "onelight"
# theme = "emacs"

[editor]
shell = ["fish", "-c"]
cursorline = true
gutters = []
auto-format = true
auto-pairs = false
bufferline = "multiple"
color-modes = true
insert-final-newline = true
popup-border = "all"
mouse = true
completion-timeout = 5
soft-wrap.enable = true

[editor.auto-save]
focus-lost = true

[editor.search]
wrap-around = false

[editor.statusline]
left = [
  "spinner",
  "version-control",
  "file-name",
  "file-modification-indicator",
  "read-only-indicator",
]
center = []
right = ["diagnostics", "position", "position-percentage", "file-type"]

[editor.lsp]
goto-reference-include-declaration = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[keys.normal]
"=" = ":fmt"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
C-S-pagedown = "goto_next_buffer"
C-S-pageup = "goto_previous_buffer"
p = "paste_clipboard_after"
P = "no_op"
y = "yank_to_clipboard"
Y = "no_op"
R = "replace_selections_with_clipboard"
d = ["yank_to_clipboard", "delete_selection_noyank"]

[keys.insert]
C-S-pagedown = "goto_next_buffer"
C-S-pageup = "goto_previous_buffer"

[keys.select]
"=" = ":fmt"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
C-S-pagedown = "goto_next_buffer"
C-S-pageup = "goto_previous_buffer"
p = "paste_clipboard_after"
P = "no_op"
y = "yank_to_clipboard"
Y = "no_op"
R = "replace_selections_with_clipboard"
d = ["yank_to_clipboard", "delete_selection_noyank"]

# fbjsdga'w/krhc
[keys.normal.space]
m = ":w"
M = ":w!"
C-c = ":config-reload"
R = ":rla"
q = ":q"
Q = ":q!"
e = ":buffer-close"
F = "no_op"
y = "no_op"
Y = "no_op"
p = "no_op"
P = "no_op"

[keys.normal.g]
n = "no_op"
p = "no_op"
j = "no_op"
k = "no_op"
t = "no_op"
c = "no_op"
b = "no_op"

[keys.select.g]
n = "no_op"
p = "no_op"
j = "no_op"
k = "no_op"
t = "no_op"
c = "no_op"
b = "no_op"
